In [1]:
import tensorflow
print(tensorflow.__version__)

2.18.0


In [ ]:
#import imp libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [ ]:
#imorting dataset
df=pd.read_csv('/content/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

## **EDA:-**

In [ ]:
#NULL DETECTION:-
df.isnull().sum().sum()

np.int64(0)

In [ ]:
#CEHCKING FOR DUPLICATED VALUES:-
df.duplicated().sum()

np.int64(0)

## **splitting of data items:-**

In [ ]:
#dividing the dataset into independent/dependent rows and columns:-
x=df.iloc[:,3:13]
y=df.iloc[:,13]

In [ ]:
x #set of independent rows

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [ ]:
y #set of independent rows

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

# **FEATURE ENGINEERING:-**

In [ ]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

## Here we have row number and customer id ...which are unique features so we need to drop it from dataset and geography and gender columns are in form of object datatype so we need to appy encoding processes.

In [ ]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1) #this is the another process of deleting cols....

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [ ]:
# Applying the encoding process:-
geography=pd.get_dummies(x['Geography'],drop_first=True)
gender=pd.get_dummies(x['Gender'],drop_first=True)

In [ ]:
# applying concatenation process:-
#1>first delete both column and thn.
#2>concate both encoded format.
x=x.drop(['Geography','Gender'],axis=1)


In [ ]:
x=pd.concat([x,geography,gender],axis=1)

In [ ]:
x

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain   Male  
0                  1        101348.88    False  False  False  
1                  1        112542.58    False   True  False  
2                  0        113931.57    False  False  False  
3                  0         93826.63    False  False  False  
4                  1         79084.10    False   True  False  
...              ...              ...      ...    ...    ...  
9995               0         96270.64    False  False   True  
9996               1        101699.77    False  False   True  
9997               1         42085.58    False  False  False  
9998               0         92888.52     True  False   True  
9999               0         38190.78    False  False  False  

[10000 rows x 11 columns]

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Age              10000 non-null  int64  
 2   Tenure           10000 non-null  int64  
 3   Balance          10000 non-null  float64
 4   NumOfProducts    10000 non-null  int64  
 5   HasCrCard        10000 non-null  int64  
 6   IsActiveMember   10000 non-null  int64  
 7   EstimatedSalary  10000 non-null  float64
 8   Germany          10000 non-null  bool   
 9   Spain            10000 non-null  bool   
 10  Male             10000 non-null  bool   
dtypes: bool(3), float64(2), int64(6)
memory usage: 654.4 KB


# **VALIDATION METHOD:-**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=34)

# FEATURE SCALING:-
ITS A METHOD WHICH IS APPLICABLE FOR OPERATIONS SUCH AS LOGISTIC REGRESSION,ANN,
LINEAR REGRESSION ETC BUT NOT APPLICABLE FOR ENSEMBLE METHOD.GENERALLY WHERE THE DISTANCE IS CALCULATED AND OPTIMIZERS ARE USED IN THAT CASE IT CAN BE USED TO INCREASE THE EFFICIEMCY.

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [ ]:
x_train

array([[ 1.0595936 , -0.07610582, -0.69606685, ...,  1.73761118,
        -0.57673443,  0.90795024],
       [ 0.48836358, -1.32238016, -0.35020085, ..., -0.57550274,
        -0.57673443, -1.10138195],
       [-0.58139445, -0.07610582,  0.34153114, ...,  1.73761118,
        -0.57673443,  0.90795024],
       ...,
       [-0.78911446, -0.45957485, -0.00433485, ..., -0.57550274,
         1.7339003 ,  0.90795024],
       [-0.55023645,  0.59496498,  0.68739714, ..., -0.57550274,
        -0.57673443,  0.90795024],
       [ 0.05215157,  0.11562869, -1.73366484, ...,  1.73761118,
        -0.57673443, -1.10138195]])

In [ ]:
x_test

array([[-0.51351694, -0.68630317,  0.68632912, ...,  1.69941898,
        -0.56503205,  0.92593473],
       [-0.86146143,  0.44100164,  0.68632912, ..., -0.58843641,
        -0.56503205, -1.07998973],
       [-0.50328328, -0.40447697, -1.38675522, ...,  1.69941898,
        -0.56503205,  0.92593473],
       ...,
       [ 0.43821357,  0.06523337,  0.68632912, ...,  1.69941898,
        -0.56503205,  0.92593473],
       [-1.40384548, -0.40447697,  1.7228713 , ..., -0.58843641,
         1.76981112,  0.92593473],
       [-0.88192875, -1.62572385,  0.68632912, ...,  1.69941898,
        -0.56503205,  0.92593473]])

# **ANN Model Building:-**

In [ ]:
#keras is a wrapper which is integrated with tensorflow.
from tensorflow.keras.models import Sequential # it provides the ann framework.
from tensorflow.keras.layers import Dense #helps to create different layer neurons.
from tensorflow.keras.layers import LeakyReLU,PReLU,ELU #activation function used in hidden and output layer.
from tensorflow.keras.layers import Dropout #used to deactivate nodes to avoid overfitting.

In [ ]:
classifier=Sequential() #installing the ann

In [ ]:
classifier.add(Dense(units=11,activation='relu')) #input layer

In [ ]:
classifier.add(Dense(units=6,activation='relu')) #1st hidden layer


In [ ]:
# classifier.add(Droupout(0.2)) #for drop- out

In [ ]:
classifier.add(Dense(units=6,activation='relu'))#2nd hidden layer


In [ ]:
classifier.add(Dense(units=1,activation='sigmoid')) #output layer

In [ ]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model_history=classifier.fit(x_train,y_train,validation_split=0.33,batch_size=10,epochs=50)

Epoch 1/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.7921 - loss: 0.5516 - val_accuracy: 0.8053 - val_loss: 0.4385
Epoch 2/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.7964 - loss: 0.4351 - val_accuracy: 0.8074 - val_loss: 0.4276
Epoch 3/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8039 - loss: 0.4339 - val_accuracy: 0.8211 - val_loss: 0.4192
Epoch 4/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8295 - loss: 0.4095 - val_accuracy: 0.8243 - val_loss: 0.4111
Epoch 5/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8266 - loss: 0.4058 - val_accuracy: 0.8304 - val_loss: 0.4014
Epoch 6/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.8408 - loss: 0.3876 - val_accuracy: 0.8389 - val_loss: 0.3867
Epoch 7/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8511 - loss: 0.3628 - val_accuracy: 0.8421 - val_loss: 0.3749
Epoch 8/50
503/503 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8603 - loss: 0.3409 - val_accuracy: 0.

In [ ]:
y_pred=classifier.predict(x_test)
y_pred = (y_pred > 0.5)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [ ]:
#confusion matrix
from sklearn.metrics import *

In [ ]:
confusion_matrix(y_test,y_pred)

array([[1873,   95],
       [ 270,  262]])

In [ ]:
# Accuracy test:-
accuracy_score(y_test,y_pred)*100

85.39999999999999